# Generated by Django 3.1.4 on 2021-02-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_auto_20210206_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_tlg',
            new_name='user_id_tlg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_promocode',
        ),
    ]
