# Generated by Django 3.1.4 on 2021-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link_telegraph',
            field=models.URLField(default='telegra.ph', verbose_name='Ссылка на статью в telegra.ph'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_link_to_original',
            field=models.URLField(default='google.com', verbose_name='Ссылка оригинала статьи, или на наш сайт.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(verbose_name='Текст статьи в html'),
        ),
    ]
