# Generated by Django 3.1.4 on 2021-02-06 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0003_auto_20210205_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_parsed_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время когда статья была пропаршена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
