# Generated by Django 3.1.4 on 2021-02-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parser', '0004_auto_20210206_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_parsed_time',
        ),
        migrations.AddField(
            model_name='article',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Была ли статья отправлена в бота'),
        ),
    ]
